# Generated by Django 4.2.1 on 2023-05-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseDate', models.DateField()),
                ('duration', models.DecimalField(decimal_places=3, max_digits=200)),
            ],
        ),
    ]
